### ISSUE TITLE
Wrong encoding

### ISSUE THREAD

**Issue by NelsonTriesCoding** [lmammino/swagger-jsdoc-generator#1] opened 2017-05-15 12:56 UTC
Hello, I'm new to JSON and Swagger and there is something I quite don't understand and I don't know if I'm doing things wrong or anything. 

I've been doing as told in the README but the final output has some kind of wrong encoding (UTF-16 LE) which produces weird characters in the doc (really annoying in my case). 

As I'm trying to script the whole process (because I have a lot of API to document, it would be really good to have the file in UTF-8  without having to mess with the file directly with my text editor. I'll find a workaround for short term usage. But for long term usage, maybe you can do something about it ?

**Comment by lmammino** [comment] 2017-05-15 18:32
Hello @NelsonTriesCoding,
first of all thanks for using this library.

Secondly, can you please specify what are the steps (or provide a repository with your setup) to reproduce the issue?

Unfortunately, I never had this issue before and it seems a rather weird one.

**Comment by NelsonTriesCoding** [comment] 2017-05-16 09:29
Well I have Swagger comment on a JS API code and a configuration file named "conf.json" which is pretty much the same as the one in your README.  When I use "swagger-jsdoc-generator conf.json > config.json" I get this weird output. By saving it with a different encoding dirrectly from VSCode, the output is a nice looking JSON but as I said I would like to script the whole process. I'll provide a sample of the output (I can't provide much more as the files aren't mine and none of my coworkers know if the client wants to keep them private).

![oups](https://cloud.githubusercontent.com/assets/26653416/26099384/cb8e9144-3a2a-11e7-8feb-08a4004cb962.png)

**Comment by lmammino** [comment] 2017-05-16 10:38
That's interesting (and weird!).
Can you try to open the file with another editor?
Also, which OS and language do you use?

**Comment by NelsonTriesCoding** [comment] 2017-05-16 12:25
I'm using Win10 and JS with basic Swagger comments

**Comment by lmammino** [comment] 2017-05-16 21:09
As far as I am aware no. Also it might be some specific windows behaviour maybe given by the output redirection? Are you using the regular shell, powershell or something else?

**Comment by NelsonTriesCoding** [comment] 2017-05-17 09:07
I'm usign Powershell (which was the default terminal in  VSCode). I also tried on bash but the input was the same (however the weird tokens where not showing, the encoding was the same so I still have to change it myself). When I'll have a bit of free time, I'll try with one of my coworker's computer to see if it's a wrong config on my computer. It doesn't seems to be from VSCode as the default encoding is set to UTF-8 so I'm a bit confused

**Comment by lmammino** [comment] 2017-05-17 10:07
Yes, i cannot about anything else at the moment! Let me know how it goes with your co-worker machine. I'll close this one for now as i cannot reproduce it!

**Closed by lmammino** 2017-05-17 10:07 UTC

**Comment by NelsonTriesCoding** [comment] 2017-05-19 09:42
Issue solved, I don't know how nor why but changing my computer default language to "English US" solved my problem. This was really weird, guess it will make a fun story for my future children "beware the haunted computer that talks with weird magical encodings".

So the problem wasn't from the package, but thanks anyway! And sorry for taking your time
